window.SAMPLE_INBOUND_CSV = `company_name,website,founding_year,stage,hq_geography,sector,founder_background,pitch_summary
NovaPay,novapay.com,2018,Series C,"London, UK",Payments,Serial fintech founders; previously built and sold PayXcel to Worldpay in 2017,"Payment orchestration platform for enterprise e-commerce processing $8bn in annual payments volume across 40 currencies. $52m ARR, EBITDA positive. Raising $90m Series C to fund expansion into APAC and LATAM."
Along,alongagents.ai,2024,Seed,"San Francisco, US",Financial Infrastructure,Ex-Salesforce VP Product and ex-Brex Head of Engineering,"AI agents that automate back-office financial operations for mid-market companies - AP/AR workflows, bank reconciliation, and month-end close. 15 paying customers, $600k ARR. Raising $4m seed."
TalentOS,talentos.io,2021,Series A,"New York, US",HR Technology,Ex-Workday Head of Product and ex-LinkedIn engineering lead,"AI-driven workforce planning platform helping mid-market companies model headcount, predict attrition, and automate compensation benchmarking. $6m ARR, 150 enterprise customers. Raising $18m Series A."
Repodo,repodo.com,2024,Pre-Seed,"Miami, US",Payments,First-time founders; ex-Amazon and ex-Nubank,"Cross-border remittance platform targeting US-to-LatAm corridors with a mobile-first app and instant settlement via local payment rails. In beta with 1,200 active users. Raising $1.5m pre-seed."
WealthArc,wealtharc.com,2018,Series B,"Zurich, Switzerland",Wealth Management Technology,Ex-UBS Head of Digital and ex-Credit Suisse private banking technology team,Portfolio aggregation and reporting software for independent wealth managers and family offices; $350bn AUM managed through the platform. $19m ARR. Raising $35m Series B.
Flychain,flychain.us,2021,Series A,"San Francisco, US",Payments,Ex-Stripe Head of Partnerships and ex-Square product lead,"Revenue-based financing and financial services for healthcare providers, embedded directly into EHR and billing workflows. $8m ARR, 200+ healthcare practice customers. Raising $12m Series A."
LegalEdge AI,legaledge.ai,2023,Seed,"San Francisco, US",Legal Technology,Ex-Kirkland & Ellis associates and ex-Harvey AI engineers,Contract review and clause extraction platform for in-house legal teams with native integrations into Salesforce and Ironclad. $800k ARR. Raising $5m seed.
Afternoon,afternoon.co.uk,2023,Seed,"London, UK",Wealth Management,Ex-Nutmeg Head of Product and ex-Moneybox design lead,"Digital wealth platform targeting UK millennials transitioning from saving to long-term investing; offers personalized portfolio management with ISA and pension wrappers. Pre-revenue, 4,000 waitlist signups. Raising £3m seed."
DeFiVault,defivault.xyz,2023,Seed,"New York, US",Crypto / DeFi Infrastructure,Ex-a16z crypto and ex-Coinbase protocol engineers,"Institutional-grade custody and yield optimization infrastructure for tokenized real-world assets, targeting banks and asset managers entering digital assets. $200k ARR from early institutional pilots. Raising $4m seed."
ClearLend,clearlend.co,2019,Series B,"New York, US",Lending,Ex-OnDeck COO and ex-Kabbage Chief Risk Officer,"Marketplace lending platform connecting SMB borrowers with 30+ institutional lenders using proprietary cash-flow underwriting. $28m ARR, $1.2bn in loans facilitated. Raising $55m Series B."
Titan,titanbanking.ai,2023,Seed,"New York, US",Banking Technology,Ex-JPMorgan technology division and ex-OpenAI researcher,"AI-native core banking components for community banks and credit unions, offering LLM-powered loan underwriting and deposit management modules. 4 community bank pilots signed. Raising $5m seed."
Verdant Analytics,verdantanalytics.io,2022,Seed,"London, UK",Climate / ESG Data,Ex-Bloomberg data and ex-McKinsey climate practice,Corporate carbon accounting and ESG reporting software for mid-market companies navigating CSRD and SEC climate disclosure requirements. $1.2m ARR. Raising $4m seed.
Koxa,koxa.io,2022,Series A,"New York, US",Payments / Banking Infrastructure,Ex-Goldman Sachs transaction banking and ex-Plaid engineering,"Banking and payments API platform enabling SMBs to connect bank accounts, automate payables and receivables, and access working capital. $5m ARR, 60% QoQ growth. Raising $15m Series A."
Cohesion,cohesionplatform.com,2022,Seed,"Chicago, US",PropTech / Real Estate,Ex-JLL technology division and ex-CBRE digital team,"Operating system for commercial real estate buildings integrating access control, energy management, and tenant experience into a unified platform. $1.1m ARR, 12 buildings under contract. Raising $5m seed."
ZeroDrift,zerodrift.ai,2024,Seed,"New York, US",Financial Infrastructure,Ex-Citadel quantitative research and ex-AWS financial services infrastructure,"Real-time financial data reconciliation infrastructure for fintechs and banks, eliminating settlement discrepancies using ML-powered matching. Two Tier-1 bank design partners signed. Raising $3m seed."
ShieldInsure,shieldinsure.com,2017,Series D,"New York, US",Insurance Technology,Serial insurtech founder; previously built and sold CoverNow to Munich Re,"Embedded insurance platform offering parametric and on-demand products via API to fintechs, neobanks, and e-commerce platforms. $80m ARR, 200+ distribution partners. Raising $120m Series D."
Paypercut,paypercut.com,2023,Seed,"Berlin, Germany",Payments,Ex-Adyen product manager and ex-Klarna growth lead,"B2B payments platform allowing freelancers and gig workers across Europe to invoice and collect payments with same-day settlement, competitive FX, and embedded insurance. $400k ARR, 3x YoY growth. Raising €2.5m seed."
MedSync,medsync.health,2022,Seed,"Boston, US",Healthcare Technology,Ex-Epic implementation lead and ex-Athenahealth product manager,"Healthcare data interoperability tools allowing providers to aggregate and normalize patient records across EMR systems for care coordination. Pre-revenue, 3 hospital pilots underway. Raising $3.5m seed."
forage,joinforage.com,2021,Series B,"San Francisco, US",Payments,Ex-Visa product and ex-payments industry veterans,"Payments API enabling retailers to accept EBT/SNAP payments online - a segment previously limited to in-store transactions only. $500m+ GMV processed, 100+ retail customers including major grocery chains. Raising $40m Series B."
PayTomo,paytomo.com,2023,Pre-Seed,Singapore,Payments,Ex-GrabPay product lead and ex-Stripe Southeast Asia,"B2B cross-border payments platform enabling SMEs across Southeast Asia to pay suppliers in local currencies with same-day settlement via regional payment rails. Pre-revenue, 8 SME pilots. Raising $1.5m pre-seed."
Helmlife,helmlife.ai,2023,Seed,"Chicago, US",Insurance,Ex-Prudential underwriting actuary and ex-Palantir data engineer,AI-powered life insurance underwriting platform helping independent brokers quote and bind policies faster using automated medical history analysis and risk scoring. $300k ARR. Raising $3m seed.
ClearRoute,clearroute.io,2021,Series A,"Chicago, US",Logistics / Supply Chain,Ex-FedEx operations director and ex-Flexport engineering lead,"Last-mile logistics optimization SaaS for regional couriers using real-time traffic and weather data to reduce delivery times by an average of 18%. $4m ARR, 30 courier clients. Raising $12m Series A."
Zaro,zaro.ai,2024,Pre-Seed,"San Francisco, US",Financial Services AI,First-time founders; ex-Anthropic and ex-Brex,"AI agents for financial compliance and regulatory reporting, automating BSA/AML filings, SAR submissions, and exam preparation for fintechs and regional banks. Pre-revenue, 2 design partnerships with regional banks. Raising $2m pre-seed."
OpenFinance Co,openfinanceco.com,2020,Series B,"London, UK",Banking Infrastructure,Ex-TrueLayer co-founder and ex-Open Banking Limited technical lead,"Open banking and PSD2 compliance infrastructure for European banks enabling account aggregation, payment initiation, and fraud detection APIs. $22m ARR, 40 bank clients. Raising $50m Series B."
Obsydian,opereit.ai,2023,Seed,"New York, US",Real Estate Technology,Ex-Blackstone real estate technology and ex-Yardi product team,"AI platform automating real estate investment analysis, lease abstraction, and asset management reporting for institutional real estate investors. $400k ARR, 8 institutional clients. Raising $3.5m seed."`;
